name: Maven Build & Test

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [17, 21]
    env:
      MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn --show-version --errors --batch-mode --update-snapshots verify
